name: Daily Data Update

on:
  schedule:
    # This will run at 1:00 UTC every day (adjust the time as needed)
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests python-dotenv alphacast
    
    - name: Create .env file
      env:
        ALPHACAST_KEY: ${{ secrets.ALPHACAST_KEY }}
      run: |
        echo "ALPHACAST_KEY=${{ secrets.ALPHACAST_KEY }}" > .env
    
    - name: Run update script
      run: |
        python main.py